config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # get "videos" => "videos#index"
  #
  # get "videos/new" => "videos#new"
  #
  # post "videos" => "videos#create"
  #
  # get "videos/:id" => "videos#show"
  #
  # get "videos/:id/edit" => "videos#edit"
  # put "videos/:id" => "videos#update"
  # delete "videos/:id" => "videos#destroy"
  #
  #
  # get "comments" => "comments#index"
  # get "comments/new" => "comments#new"
  # post "comments" => "comments#create"
  # get "comments/:id" => "comments#show"
  # get "comments/:id/edit" => "comments#edit"
  # put "comments/:id" => "comments#update"
  # delete "comments/:id" => "comments#destroy"

  root to: 'videos#index'
    get '/comments', to: 'comments#index'

    resources :videos do
      resources :comments
      member do
        put "like", to: "videos#upvote"
    end
      # resources :genres
    end
end

app/models/comment.rb
class Comment <ActiveRecord::Base
belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :videos
end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_votable
  is_impressionable
has_many :comments, dependent: :destroy
belongs_to :user

def self.search(search)
  where("LOWER(subject) LIKE ?", "%#{search.downcase}%")
  # where("content LIKE ?", "%#{search}%")
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # index
  def index
    @comments = Comment.all
  end

  # new
  def new
    @video = Video.find(params[:video_id])
    @comment = Comment.new
  end

  # create
  def create

    @video = Video.find(params[:video_id])
    @comment = Comment.create!(comment_params.merge(video: @video))
    redirect_to video_comment_path(@video, @comment)

    #
    # @comment = Comment.create(comment_params)
    #
    # redirect_to "/comments/#{@comment.id}"
  end

  #show
  def show
    @comment = Comment.find(params[:id])
  end

  # edit
  def edit

    @comment = Comment.find(params[:id])
  end

  # update
  def update

    @comment = Comment.find(params[:id])
  @video = Video.find(params[:video_id])
  @comment.update(song_params.merge(video: @video))
  redirect_to video_comment_path(@comment.video, @comment)



    # @comment = Comment.find(params[:id])
    # @comment.update(comment_params)
    #
    # redirect_to "/comments/#{@comment.id}"
  end

  # destroy
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    # redirect_to "/comments"

    redirect_to songs_path
  end

  private
  def comment_params
    params.require(:comment).permit(:text_body, :author, :date_created, :video_id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    impressionist actions: [:show], unique: [:session_hash]
  def index
    if current_user
      @videos = current_user.videos

      if params[:search]
          @videos = Video.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 6)
        else
          @videos = Video.all.order('created_at DESC').paginate(page: params[:page], per_page: 6)
        end
    else
      @videos =Video.all.paginate(page: params[:page], per_page: 6)
    end

  end


    def show
    @video = Video.find(params[:id])
    impressionist(@video)
  end

    def new
    @video = Video.new
    end


    def create

    @video = current_user.videos.build(video_params)
    @video.update(date_created: Time.now.strftime("%B %d, %Y") )

    redirect_to (video_path(@video))

  end

  def edit

 @video = current_user.videos.find(params[:id])


end

  def update
    @video = Video.find(params[:id])

    @video.update(video_params)


      redirect_to video_path(@video)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path

  end

def upvote
  @video = Video.find(params[:id])
  @video.upvote_by current_user

  redirect_to video_path(@video)

end

private
def video_params
  params.require(:video).permit(:subject, :author, :likes, :link_url, :user_id)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for([@video, @comment]) do |f| %>

  <%= f.label :text_body %>
  <%= f.text_field :text_body %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <!-- <%= f.label :date_created %> -->
  <!-- <%= f.text_field :date_created %> -->

  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render 'form' %>

<%= link_to 'Delete!', comment_path(@comment), method: :delete, class: 'delete' %>
<!--
<form action="/comments/<%= @comment.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="put">

  <label for="comment[text_body]">Body:</label>
  <input name="comment[text_body]" value="<%= @comment.text_body %>">

  <label for="comment[author]">Author:</label>
  <input name="comment[author]" value="<%= @comment.author %>">

  <label for="comment[date_created]">Date Created</label>
  <input name="comment[date_created]" value="<%= @comment.date_created %>">

  <label for="comment[video_id]">Video ID:</label>
  <input name="comment[video_id]" value="<%= @comment.video_id %>">

  <input type="submit" value="Create">
</form>

<form action="/comments/<%= @comment.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input class="button-delete" type="submit" value="Delete!">
</form> -->

app/views/comments/index.html.erb
<!-- <h2>Comments <a href="/comments/new">(+)</a></h2> -->

<ul>
  <% @comments.each do |comment| %>
  <li>
      <%= link_to "#{comment.text_body} - #{comment.video.author}",video_comment_path(comment.video,comment) %>
    </li>

  <% end %>
</ul>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render 'form' %>

<!-- <form action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="comment[text_body]">Body:</label>
  <input name="comment[text_body]">

  <label for="comment[author]">Author:</label>
  <input name="comment[author]">

  <label for="comment[date_created]">Date Created:</label>
  <input name="comment[date_created]">

  <label for="comment[video_id]">Video ID:</label>
  <input name="comment[video_id]">

  <input type="submit" value="Create">
</form> -->

app/views/comments/show.html.erb
<h2><%= @comment.text_body %> <a href="/comments/<%= @comment.id %>/edit">(edit)</a></h2>
<h3>Video Subject:<%= @comment.video.subject %></h3>

Author: <%= @comment.author %></br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brodkast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<!-- <img width="100" height="100" src="http://cliparts.co/cliparts/gTe/ozo/gTeozoEnc.jpg"/> -->
<%= favicon_link_tag 'favicon.ico' %>
</head>

<body>
  <nav class="fixed-nav-bar">
  standUP & LOL!
  <!-- <img src ="http://vignette4.wikia.nocookie.net/emojimeanings/images/0/06/160x160x23-face-with-tears-of-joy_png_pagespeed_ic_Z_mT_BlOxX.jpg/revision/latest?cb=20141103194118"></img> -->


<div class="headsup">

  <% if current_user %>
  <li>Welcome <%= current_user.email %>! </li>
  <li><a href="/videos">Videos</a></li>
  <li><a href="/comments">Comments</a></li>
  <li><a href ="/videos/new">Post Video(+)</a></li>
    <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to 'Signup', new_user_registration_path %></li>
    <li><%= link_to 'Login', new_user_session_path %></li>
  <% end %>
  <!-- <li><a href="/videos">Videos</a></li>
  <li><a href="/comments">Comments</a></li>
  <li><a href ="/videos/new">Post Video(+)</a></li> -->
</div>
</nav>
<br>
<br>

  <!-- <ul>
    <% if current_user %>
      <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to 'Signup', new_user_registration_path %></li>
      <li><%= link_to 'Login', new_user_session_path %></li>
    <% end %>
    <li><a href="/videos">Videos</a></li>
    <li><a href="/comments">Comments</a></li>
    <li><a href ="/videos/new">Post Video(+)</a></li>

  </ul> -->

<%= yield %>

</body>
</html>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>

  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :link_url %>
  <%= f.text_field :link_url %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <!-- <%= f.label :date_created %>
  <%= f.text_field :date_created %> -->

  <!-- <%= f.label :likes %> -->
  <!-- <%= f.text_field :likes %> -->

  <%= f.submit %>

<% end %>

app/views/videos/edit.html.erb
<h2>Edit Video Post</h2>

<%= render 'form' %>

<%= link_to 'Delete!', video_path(@video), method: :delete, class: 'delete' %>


<!--
<form action="/videos/<%= @video.id %>" method="post">
  <input type="hidden" name="_method" value="put">

  <label for="video[subject]">Subject:</label>
  <input name="video[subject]" value="<%= @video.subject %>">

  <label for="video[author]">Author:</label>
  <input name="video[author]" value="<%= @video.author %>">

  <label for="video[date_created]">Date Created:</label>
  <input name="video[date_created]" value="<%= @video.date_created %>">

  <label for="video[likes]">Likes:</label>
  <input name="video[likes]" value="<%= @video.likes %>">

  <label for="video[link_url]">URL:</label>
  <input name="video[link_url]" value="<%= @video.link_url %>">


  <input type="submit" value="Create">
</form>

<form action="/videos/<%= @video.id %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input class="button-delete" type="submit" value="Delete!">
</form> -->

app/views/videos/index.html.erb
<br>
<div class ="searchbox">
<%= form_tag(videos_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Videos" %>
<%= submit_tag "Search" %>
<% end %>
<%= will_paginate @videos, previous_label: "Older", next_label: "Newer" %>
</div>

<!-- <h2>brodKast Videos <a href ="/videos/new">(+)</a></h2> -->
<ul>

    <% @videos.each do |video| %>

    <li class="display">
        <a href ="/videos/<%= video.id %>">
      <iframe width="360" height="215" src="<%=video.link_url%>" frameborder="0" allowfullscreen></iframe><br>
          Subject: <%= video.subject%><br>
            Author:<%= video.author%><br>
              Date:<%= video.date_created%><br>

                Views:<%= video.impressionist_count%><br>
                Likes:<%= video.votes_for.size%><br>
                <!-- Likes:<%= video.likes%><br> -->
                <!-- <h4><%= video.votes_for.size %></h4> -->
        </a>

      <hr>
    </li>

    </ul>
    <% end %>

app/views/videos/new.html.erb
<h2>New Video Post</h2>

<%= render 'form' %>

app/views/videos/show.html.erb
<br><br>
<li class="display">

 Subject: <%= @video.subject %> <br>
 Author: <%= @video.author %><br>
 Date: <%= @video.date_created %><br>
 Likes: <%= @video.votes_for.size %><br>
<%= link_to image_tag("Like.png"), like_video_path(@video),  method: :put %><br>

<!-- # <%= "#{@video.impressionist_count} views so far!" %> -->

  <a class="links" href="/videos/<%= @video.id %>/edit">[Edit Video Post]<br><br></a>

<iframe width="550" height="315" class='artist-photo' src="<%= @video.link_url %>"></iframe>
<!-- <h4><%= @video.link_url %></h4> -->
<!-- <h4>Likes:<%= @video.likes %></h4> -->

<h3>Add Comments <%= link_to "(+)", new_video_comment_path(@video) %></h3>

  <% @video.comments.each do |comment| %>

      <%= link_to "#{comment.text_body} (#{comment.author})", video_comment_path(@video, comment) %>
<br>
  <% end %>

</li>